"""submissions table

Revision ID: 258dfe6e54d2
Revises: 8a28ac0a9e3d
Create Date: 2019-01-28 17:47:34.013585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258dfe6e54d2'
down_revision = '8a28ac0a9e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=256), nullable=True),
    sa.Column('is_good', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_timestamp'), 'submission', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_timestamp'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
